language: node_js

node_js:
    - 13

services:
    - docker

# Pre-testing installs
install:
    - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
    - echo "no tests"

script:
    # Print the docker version for logging
    - docker --version
    - docker-compose -f deployment/docker/docker-compose-build.yaml build --parallel

# Tasks to perform after the process is successful. Formatting the
# Docker username and password as below enables you to programmatically
# log in without having the password exposed in logs.
after_success:
    - echo 'Hello Udacity..3.'
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # - docker push mathson/microservice-udagram-frontend
    # - docker push mathson/microservice-udagram-api-feed
    # - docker push mathson/microservice-udagram-api-users
    - docker push mathson/microservice-udagram-nginx