version: "3"
services:
  reverseproxy:
      image: mathson/microservice-udagram-nginx
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - udagram-api-users-svc
        - udagram-api-feed-svc
  udagram-api-users-svc:
    image: mathson/microservice-udagram-api-users
    env_file:
      - env.list
  udagram-api-feed-svc:
    image: mathson/microservice-udagram-api-feed
    env_file:
      - env.list
  frontend:
    image: mathson/microservice-udagram-frontend
    ports:
      - "8100:80"
    depends_on:
        - reverseproxy
