apiVersion: v1
kind: Service
metadata:
    name: udagram-api-users-svc
    labels:
        app: api-users
        tier: backend
        component: server
        part-of: udagram-microservices
spec:
    selector:
        app: api-users
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-users
    labels:
        app: api-users
        tier: backend
        component: server
        part-of: udagram-microservices
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-users
    template:
        metadata:
            labels:
                app: api-users
        spec:
            containers:
                - name: api-users
                  image: mathson/microservice-udagram-api-users
                  imagePullPolicy: Always
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 8080
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      successThreshold: 1
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "250m"
                      limits:
                          memory: "1024Mi"
                          cpu: "500m"
                  #   ports:
                  #       - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: config-envs
                      - secretRef:
                            name: env-secret
            volumeMounts:
                - name: aws-secret
                  mountPath: "/root/.aws/"
                  readOnly: true

---
apiVersion: v1
kind: Service
metadata:
    name: udagram-api-feed-svc
    labels:
        app: api-feed
        tier: backend
        component: server
        part-of: udagram-microservices
spec:
    selector:
        app: api-feed
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-feed
    labels:
        app: api-feed
        tier: backend
        component: server
        part-of: udagram-microservices
spec:
    replicas: 2
    selector:
        matchLabels:
            app: api-feed
    template:
        metadata:
            labels:
                app: api-feed
        spec:
            containers:
                - name: api-feed
                  image: mathson/microservice-udagram-api-feed
                  imagePullPolicy: Always
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 8080
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      successThreshold: 1
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "250m"
                      limits:
                          memory: "1024Mi"
                          cpu: "500m"
                  #   ports:
                  #       - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: config-envs
                      - secretRef:
                            name: env-secret
                #   volumeMounts:
                #       - name: aws-secret
                #         mountPath: "/root/.aws/"
                #         readOnly: true

---
apiVersion: v1
kind: Service
metadata:
    name: reverse-proxy-svc
    labels:
        app: reverse-proxy
        tier: backend
        component: server
        part-of: udagram-microservices
spec:
    selector:
        app: reverse-proxy
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
    type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: reverse-proxy
    labels:
        app: reverse-proxy
        tier: backend
        component: server
        part-of: udagram-microservices
spec:
    replicas: 1
    selector:
        matchLabels:
            app: reverse-proxy
    template:
        metadata:
            labels:
                app: reverse-proxy
        spec:
            containers:
                - name: reverse-proxy
                  image: mathson/microservice-udagram-nginx
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
    name: frontend-ionic-svc
    labels:
        app: frontend-ionic
        tier: frontend
        component: server
        part-of: udagram-microservices
spec:
    selector:
        app: frontend-ionic
    ports:
        - protocol: TCP
          port: 8100
          targetPort: 80
    type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-ionic
    labels:
        app: frontend-ionic
        tier: frontend
        component: server
        part-of: udagram-microservices
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend-ionic
    template:
        metadata:
            labels:
                app: frontend-ionic
        spec:
            containers:
                - name: frontend-ionic
                  image: mathson/microservice-udagram-frontend
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  resources:
                      requests:
                          cpu: 200m
